### ISSUE TITLE
keep switching with cmd+tab, browser/OS like

### ISSUE THREAD

**Issue by lgandecki** [namikaze-40p/obsidian-tab-selector#3] opened 2024-05-28 14:04 UTC
Do you think it would be possible to modify the behavior so the tab would keep switching while holding command and pressing tab multiple times? 
I'm not sure if there is a way for the shortcut to detect whether the tab selector is already active, and to perform different actions while the command is pressed.

**Comment by namikaze-40p** [comment] 2024-05-28 17:01
Hi, @lgandecki 
In the case of MacOS, I think the combination `Cmd` + `Tab` is not available because the app switcher function is assigned by the OS.
If that is a key combination that MacOS doesn’t use, you can assign hotkeys to the Obsidian built-in commands `Go to next tab` and `Go to previous tab`,  but is it not enough?

Example...
- `Go to next tab`
	- Hotkeys: `Ctrl` + `Tab`
- `Go to previous tab`
	- Hotkeys: `Shift` + `Ctrl` + `Tab`

<img width="918" alt="hotkeys" src="https://github.com/namikaze-40p/obsidian-tab-selector/assets/160984688/a47b6b3d-0c1a-4540-9e0b-b8d5437eff59">

**Comment by lgandecki** [comment] 2024-05-28 19:09
Hi! Thanks for the update. And sorry - I meant ctri + tab of course, as command + tab is taken by MacOS.
go to next previous tab works but it doesn't utilize your great way of switching between tabs - looking at when was a given
tab last active (instead of just next/previous on the list). Also, it doesn't show anything, I'm using minimalistic Ul and by
default if I just did go to next tab l'd have no idea how many times I have to keep pushing tab, and worse than that - no idea if
The tao I'm lookind tor is even onen.
Your sollution is better but it requires a few extra steps and also learning curve when coming from many other systems
where I can just do ctrl + tab and while keeping ctrl see the list of available things to switch to (visual code, webstorm, MacOS itself, ARC browser and so on).
Also, a quick ctrl+tab just switches to the previously opened tab. And using it twice just keeps switching between two tabs. 
I actually built a prototype using your code as a base to achieve that :) And it works great

**Comment by namikaze-40p** [comment] 2024-05-29 11:53
Thanks for the detailed information! I now understand your requirements.
I'll consider a feature like tab switching in Visual Studio Code or Arc Browser.

**Comment by namikaze-40p** [comment] 2024-06-01 17:44
@lgandecki 
I added new commands and options in [v0.5.0](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.0).
Try it if you like.

**Comment by N3C2L** [comment] 2024-06-02 08:47
Hi namikaze40p.

Thanks for the plugin!

May I ask if its possible to add activate/close tabs function with mouse click when this new menu appear?
+ 
I think the commands are labeled wrong: next tab goes to previous tab.
The back action keys working fine on my side. However, do the sub modifier keys work on your side? For example try to assign ctrl+tab / ctrl+alt+tab for the next and previous tabs in the settings and then try this keys in the editor.

**Comment by namikaze-40p** [comment] 2024-06-02 16:10
Hi, @N3C2L 

Thanks for letting me know!

---
> May I ask if its possible to add activate/close tabs function with mouse click when this new menu appear?

I think I probably could, please allow me to confirm details.
Does it mean holding down the “Main modifier key”’s key and mouse click?
Or does this mean that releasing the “Main modifier key”’s key doesn't close the modal, and then operation with mouse click?

---
> I think the commands are labeled wrong: next tab goes to previous tab.

Oops, you are right. I made a mistake.
I would fix the command and option names as follows.
Sorry, I will have to ask you to re-set it after the correction.

- Commands - before → after
	- `Go to next tab` → `Go to previous tab`
	- `Go to previous tab` → `Go to next tab`
- Options - before → after
	- `Choose how to go to the previous tab` → `Choose how to go to the next tab`
	- `Back action key` → `Reverse action key`

---
> The back action keys working fine on my side. However, do the sub modifier keys work on your side? For example try to assign ctrl+tab / ctrl+alt+tab for the next and previous tabs in the settings and then try this keys in the editor.

I use macOS and `Ctrl + Tab` / `Ctrl + Alt + Tab` worked.
There may be conflicts with shortcut keys reserved by the OS.
If you are using a Windows OS, the following shortcut keys may have priority.

https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec
`Select the option(s) below to see the list of associated shortcuts.` > `Desktop shortcuts` 
→Ctrl + Alt + Tab  -  View open apps.

**Comment by namikaze-40p** [comment] 2024-06-02 17:20
@N3C2L 
> I think the commands are labeled wrong: next tab goes to previous tab.

I fixed this problem in [v0.5.1](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.1).

**Comment by N3C2L** [comment] 2024-06-03 10:46
Thanks for the fix.


> 
> > May I ask if its possible to add activate/close tabs function with mouse click when this new menu appear?
> 
> I think I probably could, please allow me to confirm details. Does it mean holding down the “Main modifier key”’s key and mouse click? Or does this mean that releasing the “Main modifier key”’s key doesn't close the modal, and then operation with mouse click?

Thanks, I think the first option would be enough:  "...holding down the “Main modifier key”’s key and mouse click.."

> I use macOS and `Ctrl + Tab` / `Ctrl + Alt + Tab` worked. There may be conflicts with shortcut keys reserved by the OS. If you are using a Windows OS, the following shortcut keys may have priority.
> 
> https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec `Select the option(s) below to see the list of associated shortcuts.` > `Desktop shortcuts` →Ctrl + Alt + Tab - View open apps.

Thank you, but as another guy mentioned in another thread: https://github.com/namikaze-40p/obsidian-tab-selector/issues/4#issue-2329887555
On Windows no other sub modifier setting work. The only working thing on Windows is set up a reverse action key + the action key  which is not "tab":

![image](https://github.com/namikaze-40p/obsidian-tab-selector/assets/74585843/b5347cf3-3927-4881-a411-05ef787b8fc3)

That example above is one the few working settings on Windows. Problem is, there is no console error visible, so I can't help here. This error appears every time, tested in a sandbox vault, only your plugin installed:

<img width="219" alt="2024-06-03 12_28_37-tgtg - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/namikaze-40p/obsidian-tab-selector/assets/74585843/c85d49c0-5138-4e17-b425-c41069b5d01c">

**Comment by namikaze-40p** [comment] 2024-06-03 12:32
>>> May I ask if its possible to add activate/close tabs function with mouse click when this new menu appear?
>>> 
>>I think I probably could, please allow me to confirm details. Does it mean holding down the “Main modifier key”’s key and mouse click? Or does this mean that releasing the “Main modifier key”’s key doesn't close the modal, and then operation with mouse click?
>>
>Thanks, I think the first option would be enough: "...holding down the “Main modifier key”’s key and mouse click.."

Thanks! I'll consider development.

---
> That example above is one the few working settings on Windows. Problem is, there is no console error visible, so I can't help here. This error appears every time, tested in a sandbox vault, only your plugin installed:

Thanks for your help!

In [v0.5.2](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.2), error logs are output to the console when this event occurs.
Can you show me the logs of the output?

1. Open develop tool by `Ctrl + Shift + I` shortcut key.
2. Click the `Console` tab.
3. Capture the output logs.

Incidentally I also use Windows by Parallels Desktop, but `Ctrl + Tab` and `Ctrl + Shift + Tab` work correctly...

**Comment by N3C2L** [comment] 2024-06-03 13:16
Thanks. Did you try it in a sandbox vault with only your plugin enabled under Windows? 
Here is the error from the console. Tab selector default settings:

<img width="332" alt="2024-06-03 15_13_21-Untitled 1 - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/namikaze-40p/obsidian-tab-selector/assets/74585843/7f272816-3dcb-4d7d-8298-a9541519bb8b">

<img width="322" alt="2024-06-03 15_13_43-Untitled 1 - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/namikaze-40p/obsidian-tab-selector/assets/74585843/d04365b7-d791-4eb2-97a9-e2b0f0a505b2">

**Comment by namikaze-40p** [comment] 2024-06-03 16:43
Thanks!

> Thanks. Did you try it in a sandbox vault with only your plugin enabled under Windows?

Sorry, I tried that same situation and reproduced the bug.
However, your information has helped me identify the cause.

https://docs.obsidian.md/Reference/TypeScript+API/Modifier
There is a difference in the value of the modifier key between Windows and macOS, but I have been using only the macOS value until v0.5.2.

I fixed in [v0.5.3](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.3).
Could you try again with the latest version?

**Comment by N3C2L** [comment] 2024-06-03 17:20
Can confirm it's working on my side!
Thanks a bunch for fixing it!  👍

**Comment by namikaze-40p** [comment] 2024-06-04 03:08
That was good! Thanks for your help too!

---
>May I ask if its possible to add activate/close tabs function with mouse click when this new menu appear?

I have largely implemented this feature.
Please wait a little longer for the release when the final adjustments are made.

**Comment by namikaze-40p** [comment] 2024-06-04 15:35
@N3C2L 
> May I ask if its possible to add activate/close tabs function with mouse click when this new menu appear?

I released it in [v0.5.4](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.4).
Try it if you like.

**Comment by N3C2L** [comment] 2024-06-04 20:59
Thanks! I can activate them, but how can I close them?
I don't want to pressure you, but would it be possible to add these fantastic buttons, similar to those in your tab selector, to this new menu?
<img width="82" alt="2024-06-04 22_53_22-Start Here - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/namikaze-40p/obsidian-tab-selector/assets/74585843/5c600af6-1524-4cf7-b552-32eaa3531a69">

**Comment by namikaze-40p** [comment] 2024-06-05 03:13
Sorry, I forgot to add the closing UI.
I'll consider development. It may take a little time, but please wait.

**Comment by namikaze-40p** [comment] 2024-06-07 14:38
@N3C2L 
>> Thanks! I can activate them, but how can I close them?
>>
> Sorry, I forgot to add the closing UI.

I released it in [v0.5.6](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.6).
Try it if you like.

**Comment by N3C2L** [comment] 2024-06-07 17:25
Great, thanks! The buttons for closing are working fine!
 I increased the font size to 17px with a css snippet for the tab titles in the modal:
.modal.tab-history-modal .th-leaf-name {
    font-size: 17px;
}
..but that's just a personal preference because of my eyes 😄

**Comment by N3C2L** [comment] 2024-06-07 20:31
I'm sorry, but I think the newest update of obsidian to v1.6.2 produces a new problem (because your plugin was working before the obsidian update on my side).
Can you test the shortcut for previous tab command set to ctrl+tab in Windows in a sandbox vault? Because on my side only ctrl+shift+tab for the next tab is working, but not ctrl+tab for the previous tab.

**Comment by N3C2L** [comment] 2024-06-07 20:51
Oh, it's not your plugin! It's a bug from the new Obsidian version 1.6.2 itself! In the new Obsidian version you can't assign ctrl+tab to other commands (at least on Windows), you can try it. We have to wait for the new Obsidian patch. Then ctrl+tab will work again in your plugin under Windows.

**Comment by namikaze-40p** [comment] 2024-06-07 23:19
Thanks for trying!

---
> I increased the font size to 17px with a css snippet for the tab titles in the modal:

I agree with you.
The current font size is not legible, so I will increase the default size slightly in a few days.

---
>> Can you test the shortcut for previous tab command set to ctrl+tab in Windows in a sandbox vault? Because on my side only ctrl+shift+tab for the next tab is working, but not ctrl+tab for the previous tab.
>>
> Oh, it's not your plugin! It's a bug from the new Obsidian version 1.6.2 itself! In the new Obsidian version you can't assign ctrl+tab to other commands (at least on Windows), you can try it.

 I could used shortcut for previous tab command set to ctrl+tab in Windows in a sandbox vault, and in Obsidian version 1.6.2.
As a test, I assigned Ctrl + Tab to the “Open settings" command and it can open settings.
Do this mean that when you press ctrl+tab nothing happens in your preference?

**Comment by N3C2L** [comment] 2024-06-16 17:04
Thanks for your updates! 
It's alright now, I have no problems with it.
Thanks for making this extension!

**Comment by namikaze-40p** [comment] 2024-06-17 03:12
Thank you too for helping me check it works!
Please contact me if you have any further requests.

**Closed as completed by namikaze-40p** 2024-06-17 03:12 UTC
Labels: enhancement
