### ISSUE TITLE
Incorrect settings for Move to next/previous tab

### ISSUE THREAD

**Issue by kmaustral** [namikaze-40p/obsidian-tab-selector#4] opened 2024-06-02 22:15 UTC
Thanks for this wonderful plugin. 

I set the hotkeys to match those in the settings, but I get an error message the "Tab Selector has incorrect settings". I have the default settings:

![image](https://github.com/namikaze-40p/obsidian-tab-selector/assets/73867063/0605897c-9126-479b-a0e7-a55120c8cd1a)

This occurs if I select go to Next or Previous tab in the command pallette as well.

**Comment by namikaze-40p** [comment] 2024-06-03 00:07
Hi, @kmaustral 

Thanks for letting me know!

The settings have been corrected in the update from Version 0.5.0 to Version 0.5.1.
Sorry, I think this may be an effect of this update.
Could you please recheck the hotkey settings?

| Command                          | Version 0.5.0      | Version 0.5.1 (Latest) |
| -------------------------------- | ------------------ | ---------------------- |
| Tab Selector: Go to next tab     | Ctrl + Tab         | Ctrl + Shift + Tab     |
| Tab Selector: Go to previous tab | Ctrl + Shift + Tab | Ctrl + Tab             |

**Comment by kmaustral** [comment] 2024-06-03 02:00
I'm using the correct setting for the latest version 0.5.1. But I get the error message when I go through the command menu as well. This is on Windows.

**Comment by namikaze-40p** [comment] 2024-06-03 03:58
Old setting values may still remain inside Obsidian.
Could you please try again after pressing the reset button for `Choose how to go to next tab` in the `Tab Seletor` settings page?

If that doesn't solve the problem, could you please uninstall and reinstall the `Tab Selector` plugin and try again?

<img width="533" alt="settings" src="https://github.com/namikaze-40p/obsidian-tab-selector/assets/160984688/a9ced515-beaa-4d79-bc93-fb13c1c85bd3">

**Comment by kmaustral** [comment] 2024-06-03 12:18
I've reinstalled, but still getting the same error.

**Comment by namikaze-40p** [comment] 2024-06-03 12:42
Sorry I couldn't solve the problem.
[Other Issue](https://github.com/namikaze-40p/obsidian-tab-selector/issues/3) also reports the same problem, in case Windows.

I also use Windows by Parallels Desktop, but `Ctrl + Tab` and `Ctrl + Shift + Tab` work correctly...

In [v0.5.2](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.2), error logs are output to the console when this event occurs.
Can you show me the logs of the output?

1. Open develop tool by `Ctrl + Shift + I` shortcut key.
2. Click the `Console` tab.
3. Capture the output logs.

**Comment by namikaze-40p** [comment] 2024-06-03 16:46
Identified the cause and I fixed in [v0.5.3](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.3).
Can you please try again with the latest version as it has probably been resolved?

**Comment by kmaustral** [comment] 2024-06-03 21:02
Thanks. It works fine now. Well done.

**Comment by namikaze-40p** [comment] 2024-06-04 03:10
That was good! Thanks for using it!

**Closed as completed by namikaze-40p** 2024-06-04 03:10 UTC
Labels: bug
